### ISSUE TITLE
Blue Agent actions are not as expected.

### ISSUE THREAD

**Issue by soledo** [ORNL/cyberwheel#3]
hello. I have a few questions about the cyber wheel demo.

The behavior of the blue agent is defined as deploying decoys, removing decoys, or doing nothing as described in the documentation.

However, according to the dynamic_blue_agent.yaml in the resource, it seems to only use “nothing” and “deploydecoy”.

In cyberwheel_dynamic.py, the comment for blue_config says that blue_agent_config.yaml is the default, but I can't find that file in this repository, so my guess is that this file is using all the actions.

After all, the blue agent's actions only reference dynamic_blue_agent.yaml, so if I'm misunderstanding the code, I'd appreciate some advice.

**Comment by chaulagaina** [comment]
The comment in the dynamic_blue.py file looks like it may just be a typo, there isn't a file currently referenced called blue_agent_config.yaml. The file used by default is the dynamic_blue_agent.yaml file, and it currently has the actions for deploying a decoy, and for doing nothing. However, you can add more actions that are defined in blue_actions/actions. For example, to add the remove action to the blue agent, you can add this code in the actions section of the YAML file:

```yml
remove_decoy: # Unique name for the action
    module: RemoveDecoyHost # Name of the module of the blue action
    class: RemoveDecoyHost # Name of the class of the blue action
    configs: # Defines configs if applicable, none are needed for the remove action.
    reward: # Defines rewards
        immediate: 0 # no short-term cost or benefit to removing decoys
        recurring: 0 # no long-term cost or benefit to removing decoys
    action_space_args: # Info needed to define action space
        type: subnet # Type of target for this action : 'standalone' (no target) | 'subnet' | 'host'
    shared_data: # No data to share
```

This references the RemoveDecoyHost module. This configurability also allows you to be able to create your own blue agent actions as modules in the blue_actions/actions directory and define them in the YAML.

Let me know if you have any more questions about this!
